# from (2025-10-23): https://raw.githubusercontent.com/wg-easy/wg-easy/master/docker-compose.yml

name: ${PROJECT_NAME}

volumes:
  etc_wireguard:
  caddy_config:
  caddy_data:

services:
  caddy:
    container_name: ${PROJECT_NAME}-caddy
    image: caddybuilds/caddy-cloudflare:2.10.2-alpine
    # publish everything you deem necessary
    environment:
      # These must be in .env, used in 'ports' section
      - CLIENT_HTTP_PORT
      - CLIENT_HTTPS_PORT
    env_file: "secrets.env"
    ports:
      - '2019:2019/tcp'  # admin portal
      - '${CLIENT_HTTP_PORT}:${CLIENT_HTTP_PORT}/tcp'
      - '${CLIENT_HTTPS_PORT}:${CLIENT_HTTPS_PORT}/tcp'
      - '${CLIENT_HTTPS_PORT}:${CLIENT_HTTPS_PORT}/udp'
      # for couchdb
      - '5985:5985/tcp'
      # for jellyfin
      - '7074:7074/tcp'
    networks:
      - caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:ro'
      - caddy_config:/config
      - caddy_data:/data
    develop:
      watch:
        - action: "restart"
          path: "Caddyfile"

  wg-easy:
    container_name: ${PROJECT_NAME}-wg-easy
    build:
      context: "wg-easy"
      dockerfile: "Dockerfile"
    depends_on: 
      - caddy
    environment:
      # Caddy reverse-proxy port
      - PORT=80
      # for new clients: Only route internal VPN subnet; no Internet traffic
      - WG_ALLOWED_IPS=10.8.0.0/24
    networks:
      caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      # "80:80"  # NOTE: http server now reverse-proxied
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    develop:
      watch:
        - action: "rebuild"
          path: "wg-easy"


networks:
  caddy:
    name: ${PROJECT_NAME}-caddy
